FROM registry.fedoraproject.org/fedora-toolbox:43 AS base

FROM base AS packages
ENV PATH="/root/.local/bin:${PATH}"

COPY packages /
RUN dnf -y --setopt=install_weak_deps=False install $(<packages) \
    && rm /packages

FROM packages AS runner
RUN pipx install poetry black
