FROM registry.fedoraproject.org/fedora-toolbox:43
ARG USER_SHELL
ENV PATH="/root/.local/bin:${PATH}"
COPY packages /
RUN dnf -y --setopt=install_weak_deps=False install $(<packages) \
    && rm /packages

RUN pipx install poetry black alembic
