services:
  db:
    image: postgis/postgis:18-3.6-alpine
    env_file:
      - .db.env
    volumes:
      - pg_data:/var/lib/postgresql
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
  #     network: host
  #   volumes:
  #     - ./:/usr/lib/agro_api
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - PYTHONPATH=/usr/lib/agro_api/.venv
  #     - DATABASE_URL="postgresql+psycopg://api_user:Agr0_420@db:5432/agro_db"
  #     - ENVIRONMENT=development
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   stdin_open: true
  #   tty: true

volumes:
  pg_data:
  # python_packages:
  # poetry_cache:
  # pip_cache:
