"""create soil_classifications and field_soil_classifictions tables

Revision ID: 911d985bbe71
Revises: 176ff20e0efb
Create Date: 2026-03-20 16:05:19.870759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911d985bbe71'
down_revision: Union[str, Sequence[str], None] = '176ff20e0efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_classifications',
    sa.Column('name', sa.String(length=100), nullable=False, comment="Soil type name, e.g., 'Latossolos', 'Chernozem'"),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Classification system, e.g., 'SiBCS', 'WRB'"),
    sa.Column('parent_id', sa.Uuid(), nullable=True, comment='\n        For hierarchical systems: parent soil type\n        (e.g., order → suborder)\n        '),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['soil_classifications.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'source', name='uq_soil_name_source')
    )
    op.create_table('field_soil_classifications',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('soil_classification_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soil_classification_id'], ['soil_classifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('field_id', 'soil_classification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_soil_classifications')
    op.drop_table('soil_classifications')
    # ### end Alembic commands ###
