"""create field_transitions table

Revision ID: ea188c3b45dc
Revises: 911d985bbe71
Create Date: 2026-03-20 16:06:18.942282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea188c3b45dc'
down_revision: Union[str, Sequence[str], None] = '911d985bbe71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_transitions',
    sa.Column('predecessor_id', sa.Uuid(), nullable=False, comment='The field that existed before'),
    sa.Column('successor_id', sa.Uuid(), nullable=False, comment='The field that came after'),
    sa.Column('kind', sa.String(length=64), nullable=False, comment='What kind of transition'),
    sa.Column('transitioned_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False, comment='When the transition happened'),
    sa.Column('transitioned_by_id', sa.Uuid(), nullable=False, comment='User who performed the transition'),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predecessor_id != successor_id', name='ck_field_transition_no_self_reference'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['successor_id'], ['fields.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transitioned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('predecessor_id', 'successor_id', 'kind', name='uq_field_transition')
    )
    op.create_index(op.f('ix_field_transitions_predecessor_id'), 'field_transitions', ['predecessor_id'], unique=False)
    op.create_index(op.f('ix_field_transitions_successor_id'), 'field_transitions', ['successor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_transitions_successor_id'), table_name='field_transitions')
    op.drop_index(op.f('ix_field_transitions_predecessor_id'), table_name='field_transitions')
    op.drop_table('field_transitions')
    # ### end Alembic commands ###
