"""add slope data columns to fields table

Revision ID: fdbcce893d9a
Revises: 1ae47672ebfc
Create Date: 2026-03-20 20:07:41.968581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbcce893d9a'
down_revision: Union[str, Sequence[str], None] = '1ae47672ebfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('slope_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='Slope in percent: measured or estimated'))
    op.add_column('fields', sa.Column('slope_class', sa.String(length=50), nullable=True, comment='SlopeClass enum: classified automatically if slope_percent informed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'slope_class')
    op.drop_column('fields', 'slope_percent')
    # ### end Alembic commands ###
