"""create estates table

Revision ID: bc39edbfd9b2
Revises: 966574bebc3f
Create Date: 2026-03-20 15:50:47.103201

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc39edbfd9b2'
down_revision: Union[str, Sequence[str], None] = '966574bebc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('address_id', sa.Uuid(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.Date(), nullable=True),
    sa.Column('label', sa.String(length=96), nullable=False, comment='Human-readable Estate name'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL-friendly identifier'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=16), nullable=False, comment='API validation with EstateZone Enum'),
    sa.Column('usage', sa.String(length=50), nullable=True, comment='API validation with EstateUsage Enum'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='API validation with EstateStatus Enum'),
    sa.Column('ownership_type', sa.String(length=50), nullable=False, comment='API validation with OwnershipType Enum'),
    sa.Column('declared_area_m2', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('entrance_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Estate access location (geographic data)'),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Estate boundary as a multipolygon geometry'),
    sa.Column('boundary_source', sa.String(length=32), nullable=True, comment='API validation with GeometrySource Enum'),
    sa.Column('perimeter_m', sa.Numeric(precision=14, scale=2), sa.Computed('\n            CASE\n                WHEN boundary IS NOT NULL\n                THEN ST_Perimeter(boundary::geography)\n                ELSE NULL\n            END\n            ', persisted=True), nullable=True, comment='Automatically updated when boundary changes'),
    sa.Column('calculated_area_m2', sa.Numeric(precision=14, scale=2), sa.Computed('\n            CASE\n                WHEN boundary IS NOT NULL\n                THEN ST_Area(boundary::geography)\n                ELSE NULL\n            END\n            ', persisted=True), nullable=True, comment='Automatically updated when boundary changes'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('declared_area_m2 IS NULL OR declared_area_m2 > 0', name='ck_estate_positive_declared_area'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_account_estate_slug')
    )
    op.create_index(op.f('ix_estates_slug'), 'estates', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estates_slug'), table_name='estates')
    op.drop_table('estates')
    # ### end Alembic commands ###
