"""create activities table

Revision ID: 22facfa4e3a1
Revises: c516ee7d126d
Create Date: 2026-03-16 20:42:50.289397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22facfa4e3a1'
down_revision: Union[str, Sequence[str], None] = 'c516ee7d126d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('activity_type', sa.String(length=50), nullable=False, comment='Polymorphic discriminator indicating object type.Ex: planting, grazing, processing...'),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False, comment='ActivityKind enum'),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('total_area_m2', sa.Numeric(precision=12, scale=2), nullable=True, comment='Area this activity covers (validate against field area)'),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('finished_at IS NULL OR finished_at >= started_at'),
    sa.CheckConstraint('total_area_m2 IS NULL OR total_area_m2 > 0', name='ck_activity_area_positive'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_field_id'), 'activities', ['field_id'], unique=False)
    op.create_index(op.f('ix_activities_started_at'), 'activities', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activities_started_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_field_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
