"""create plants table

Revision ID: 280b4829846e
Revises: 3be17453e2a8
Create Date: 2026-03-15 18:17:51.829709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280b4829846e'
down_revision: Union[str, Sequence[str], None] = '3be17453e2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plant_cycle', sa.String(length=50), nullable=True),
    sa.Column('growth_habit', sa.String(length=50), nullable=True),
    sa.Column('primary_use', sa.String(length=50), nullable=True),
    sa.Column('secondary_uses', sa.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('max_height_cm', sa.Integer(), nullable=True),
    sa.Column('min_temperature_c', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('max_temperature_c', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('water_requirement', sa.String(length=50), nullable=True),
    sa.Column('days_to_maturity', sa.Integer(), nullable=True),
    sa.Column('days_to_germination', sa.Integer(), nullable=True),
    sa.Column('drought_tolerance', sa.String(length=32), nullable=True),
    sa.Column('frost_tolerance', sa.String(length=32), nullable=True),
    sa.Column('flood_tolerance', sa.String(length=32), nullable=True),
    sa.Column('soil_ph_min', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('soil_ph_max', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('recommended_altitude_min_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recommended_altitude_max_m', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nitrogen_fixing', sa.Boolean(), nullable=False, comment='Fixes atmospheric nitrogen (legumes)'),
    sa.Column('allelopathic', sa.Boolean(), nullable=False, comment='Suppresses growth of other plants'),
    sa.CheckConstraint('min_temperature_c IS NULL OR max_temperature_c IS NULL OR max_temperature_c >= min_temperature_c', name='ck_plant_temperature_order'),
    sa.CheckConstraint('recommended_altitude_min_m IS NULL OR recommended_altitude_max_m IS NULL OR recommended_altitude_max_m >= recommended_altitude_min_m', name='ck_plant_altitude_order'),
    sa.CheckConstraint('soil_ph_max IS NULL OR (soil_ph_max >= 0 AND soil_ph_max <= 14)', name='ck_plant_ph_max_range'),
    sa.CheckConstraint('soil_ph_min IS NULL OR (soil_ph_min >= 0 AND soil_ph_min <= 14)', name='ck_plant_ph_min_range'),
    sa.CheckConstraint('soil_ph_min IS NULL OR soil_ph_max IS NULL OR soil_ph_max >= soil_ph_min', name='ck_plant_ph_order'),
    sa.ForeignKeyConstraint(['id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
