"""create organism_common_names table

Revision ID: 28191d064f58
Revises: e060501952a9
Create Date: 2026-03-15 15:24:13.942883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28191d064f58'
down_revision: Union[str, Sequence[str], None] = 'e060501952a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organism_common_names',
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True, comment='Region where the name is commonly used'),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_preferred', sa.Boolean(), nullable=False, comment='Preferred name for display in this language/region'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organism_id', 'name', 'language', name='uq_organism_name_lang')
    )
    op.create_index('idx_common_name_search', 'organism_common_names', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_common_name_search', table_name='organism_common_names')
    op.drop_table('organism_common_names')
    # ### end Alembic commands ###
