"""add jti to users table

Revision ID: 2feff8a1d25b
Revises: e158cff5594c
Create Date: 2025-12-31 14:27:52.443311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2feff8a1d25b'
down_revision: Union[str, Sequence[str], None] = 'e158cff5594c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jti', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'users', ['jti'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'jti')
    # ### end Alembic commands ###
