"""create organism_synonyms table

Revision ID: 3be17453e2a8
Revises: 28191d064f58
Create Date: 2026-03-15 15:31:43.765858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3be17453e2a8'
down_revision: Union[str, Sequence[str], None] = '28191d064f58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organism_synonyms',
    sa.Column('organism_id', sa.Uuid(), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=False),
    sa.Column('taxonomy', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full taxonomic classification previous to current one'),
    sa.Column('authorship', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organism_id'], ['organisms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organism_id', 'scientific_name', name='uq_organism_synonym')
    )
    op.create_index(op.f('ix_organism_synonyms_organism_id'), 'organism_synonyms', ['organism_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organism_synonyms_organism_id'), table_name='organism_synonyms')
    op.drop_table('organism_synonyms')
    # ### end Alembic commands ###
