"""create field_protections table

Revision ID: 624041314866
Revises: c68b4ff18539
Create Date: 2026-03-15 11:11:31.077846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624041314866'
down_revision: Union[str, Sequence[str], None] = 'c68b4ff18539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_protections',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=True, comment='What is the reason this field is protected, related to kind'),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('started_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > started_at', name='ck_field_protection_expiry'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_field_active_protection', 'field_protections', ['field_id'], unique=True, postgresql_where=sa.text('expires_at IS NULL OR expires_at > now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_field_active_protection', table_name='field_protections', postgresql_where=sa.text('expires_at IS NULL OR expires_at > now()'))
    op.drop_table('field_protections')
    # ### end Alembic commands ###
