"""create rbac tables

Revision ID: 8be9788785a7
Revises: b3cf620484fb
Create Date: 2026-03-13 18:59:45.286581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be9788785a7'
down_revision: Union[str, Sequence[str], None] = 'b3cf620484fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource', 'action', name='uq_permission_resource_action')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('estate_registries',
    sa.Column('estate_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Registration code within the competent public agency/entity'),
    sa.Column('source', sa.String(length=128), nullable=False, comment='Public agency/entity that issued the registration'),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'ACTIVE', 'PENDING', 'ANALYZING', 'SUSPENDED', 'CANCELED', 'REJECTED', 'NEEDS_CORRECTION', name='registrystatus'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expiry_date IS NULL OR issued_at IS NULL OR expiry_date >= issued_at', name='ck_registry_expiry_after_issued'),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_registry_code_not_empty'),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estate_id', 'code', name='uq_estate_registry_code')
    )
    op.create_index(op.f('ix_estate_registries_estate_id'), 'estate_registries', ['estate_id'], unique=False)
    op.create_index('ix_estate_registry_code', 'estate_registries', ['code'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_index('ix_estate_registry_code', table_name='estate_registries')
    op.drop_index(op.f('ix_estate_registries_estate_id'), table_name='estate_registries')
    op.drop_table('estate_registries')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
