"""create estates table

Revision ID: 9c9343b9ec8e
Revises: 55b4f0b36b80
Create Date: 2026-03-13 00:38:46.233494

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9343b9ec8e'
down_revision: Union[str, Sequence[str], None] = '55b4f0b36b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('deleted_at', sa.Date(), nullable=True),
    sa.Column('label', sa.String(length=96), nullable=False, comment='Human-readable name'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL-safe identifier'),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('RURAL', 'INTRAURBAN', 'PERIURBAN', name='estatekind'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PENDING', 'ARCHIVED', name='estatestatus'), nullable=False),
    sa.Column('ownership_type', sa.Enum('OWNED', 'LEASED', 'MANAGED', name='ownershiptype'), nullable=False),
    sa.Column('declared_area_m2', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('entrance_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Estate access location (geographic data)'),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Always 4326 (universal exchange format)'),
    sa.Column('boundary_source', sa.Enum('survey', 'satellite', 'manual', 'imported', name='geometrysource'), nullable=True),
    sa.Column('perimeter_m', sa.Numeric(precision=16, scale=2), sa.Computed('\n            CASE\n                WHEN boundary IS NOT NULL\n                THEN ST_Perimeter(boundary::geography)\n                ELSE NULL\n            END\n            ', persisted=True), nullable=True, comment='Automatically updated when boundary changes'),
    sa.Column('calculated_area_m2', sa.Numeric(precision=16, scale=2), sa.Computed('\n            CASE\n                WHEN boundary IS NOT NULL\n                THEN ST_Area(boundary::geography)\n                ELSE NULL\n            END\n            ', persisted=True), nullable=True, comment='Automatically updated when boundary changes'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('declared_area_m2 IS NULL OR declared_area_m2 > 0', name='ck_estate_positive_declared_area'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='idx_account_estate_slug')
    )
    op.create_index('idx_estates_boundary', 'estates', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_estates_entrance_point', 'estates', ['entrance_point'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_estates_slug'), 'estates', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estates_slug'), table_name='estates')
    op.drop_index('idx_estates_entrance_point', table_name='estates', postgresql_using='gist')
    op.drop_index('idx_estates_boundary', table_name='estates', postgresql_using='gist')
    op.drop_table('estates')
    # ### end Alembic commands ###
