"""create estate_registries table

Revision ID: b5303cf649a7
Revises: 1c1379f49165
Create Date: 2026-03-15 10:28:41.119175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5303cf649a7'
down_revision: Union[str, Sequence[str], None] = '1c1379f49165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estate_registries',
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False, comment='Registration code with the competent public agency'),
    sa.Column('source', sa.String(length=128), nullable=False, comment='Public agency/entity that issued the registration'),
    sa.Column('submitted_at', sa.Date(), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(code)) > 0', name='ck_registry_code_not_empty'),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estate_id', 'source', 'code', name='uq_estate_registry_code')
    )
    op.create_index(op.f('ix_estate_registries_estate_id'), 'estate_registries', ['estate_id'], unique=False)
    op.create_index('ix_estate_registry_code', 'estate_registries', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_estate_registry_code', table_name='estate_registries')
    op.drop_index(op.f('ix_estate_registries_estate_id'), table_name='estate_registries')
    op.drop_table('estate_registries')
    # ### end Alembic commands ###
