"""create fields table

Revision ID: c60ef81ebb42
Revises: 8be9788785a7
Create Date: 2026-03-14 21:53:49.609500

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c60ef81ebb42'
down_revision: Union[str, Sequence[str], None] = '8be9788785a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fields',
    sa.Column('estate_id', sa.UUID(), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL-safe identifier within Estate'),
    sa.Column('label', sa.String(length=96), nullable=False, comment='Human-readable name'),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False, comment='Field boundary polygon'),
    sa.Column('boundary_source', sa.Enum('survey', 'satellite', 'manual', 'imported', name='geometrysource'), nullable=True),
    sa.Column('calculated_area_m2', sa.Numeric(precision=16, scale=2), sa.Computed('ST_Area(boundary::geography)', persisted=True), nullable=False, comment='Computed measurement'),
    sa.Column('perimeter_m', sa.Numeric(precision=12, scale=2), sa.Computed('ST_Perimeter(boundary::geography)', persisted=True), nullable=False, comment='Computed measurement'),
    sa.Column('active_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('active_to', sa.Date(), nullable=True, comment='NULL means currently active'),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estate_id', 'slug', name='uq_estate_field_slug')
    )
    op.create_index(op.f('ix_fields_slug'), 'fields', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fields_slug'), table_name='fields')
    op.drop_table('fields')
    # ### end Alembic commands ###
