"""create organisms table

Revision ID: e060501952a9
Revises: faa666321a4d
Create Date: 2026-03-15 15:16:31.369161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e060501952a9'
down_revision: Union[str, Sequence[str], None] = 'faa666321a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisms',
    sa.Column('organism_type', sa.String(length=50), nullable=False, comment='Polymorphic discriminator: plant, animal, fungus, bacterium'),
    sa.Column('taxonomy', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full taxonomic classification'),
    sa.Column('scientific_name', sa.String(length=200), nullable=False, comment='Binomial nomenclature: Genus species'),
    sa.Column('authorship', sa.String(length=200), nullable=True, comment='Taxonomic authority, who named the organism: e.g. (L.) Merr.'),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='External API identifiers'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scientific_name', name='uq_organism_scientific_name')
    )
    op.create_index(op.f('ix_organisms_scientific_name'), 'organisms', ['scientific_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organisms_scientific_name'), table_name='organisms')
    op.drop_table('organisms')
    # ### end Alembic commands ###
