"""create soil_analyses table

Revision ID: faa666321a4d
Revises: fe168747cd7e
Create Date: 2026-03-15 14:43:19.289432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'faa666321a4d'
down_revision: Union[str, Sequence[str], None] = 'fe168747cd7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soil_analyses',
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('collected_at', sa.Date(), nullable=False),
    sa.Column('analyzed_at', sa.Date(), nullable=True, comment='Date laboratory issued the results'),
    sa.Column('sampling_depth_cm', sa.Integer(), nullable=False, comment='Sampling depth in centimeters. Typically 0-20cm or 20-40cm'),
    sa.Column('ph_h2o', sa.Numeric(precision=3, scale=1), nullable=True, comment='pH em água (0-14)'),
    sa.Column('base_saturation_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('organic_matter_g_dm3', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('texture_class', sa.String(length=50), nullable=True, comment='Textural classification. Ex: clayey, medium, sandy, etc'),
    sa.Column('chemical', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Chemical characteristics: ph, organic_matter, macro and micronutrients'),
    sa.Column('physical', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Physical characteristics: texture, density, porosity, water retention'),
    sa.Column('biological', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Biological characteristics: microbial biomass, respiration, nitrogen'),
    sa.Column('collector_name', sa.String(length=255), nullable=False),
    sa.Column('collector_registry', sa.String(length=64), nullable=False),
    sa.Column('laboratory_name', sa.String(length=255), nullable=False),
    sa.Column('laboratory_protocol', sa.String(length=128), nullable=True, comment='Laboratory report or protocol number'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('analyzed_at IS NULL OR analyzed_at >= collected_at', name='ck_analysis_date_after_collection'),
    sa.CheckConstraint('ph_h2o IS NULL OR (ph_h2o >= 0 AND ph_h2o <= 14)', name='ck_ph_h2o_range'),
    sa.CheckConstraint('sampling_depth_cm > 0', name='ck_dsampling_epth_positive'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil_analyses_collected_at'), 'soil_analyses', ['collected_at'], unique=False)
    op.create_index(op.f('ix_soil_analyses_field_id'), 'soil_analyses', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soil_analyses_field_id'), table_name='soil_analyses')
    op.drop_index(op.f('ix_soil_analyses_collected_at'), table_name='soil_analyses')
    op.drop_table('soil_analyses')
    # ### end Alembic commands ###
