"""create journal_entries table

Revision ID: fe168747cd7e
Revises: 5c02591b5b72
Create Date: 2026-03-15 11:49:59.726424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe168747cd7e'
down_revision: Union[str, Sequence[str], None] = '5c02591b5b72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('entity_type', sa.String(length=50), nullable=False, comment='Validated by API layer'),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(content)) > 0', name='ck_journal_entry_content_not_empty'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_author_id'), 'journal_entries', ['author_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_entity_id'), 'journal_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_journal_entries_logged_at'), 'journal_entries', ['logged_at'], unique=False)
    op.create_index('ix_journal_entry_entity', 'journal_entries', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_entry_entity', table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_logged_at'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entity_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_author_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
