FROM docker.io/postgis/postgis:18-3.6-alpine

# schema aplicado automaticamente na inicialização
COPY migrations/schema.sql /docker-entrypoint-initdb.d/01_schema.sql
COPY migrations/seed_data.sql /docker-entrypoint-initdb.d/02_seeds.sql
